project:
  type: book
  output-dir: "/Users/cuongpham/Documents/GitHub/tuhocr/"
book:
  title: "book"
  author: "Dr Cuong Pham"
  date: "5/7/2025"
  chapters:
    - index.qmd
    - Q3_v1.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

